title: Flame.ga » Free OP Server
description: Flame.ga provides you a powerful experience in Minecraft. On this server, you can do whatever you want, without any consequenses; grief, troll, use hacks - you name it.
url: https://flame.ga
author: Flame.ga
exclude:
  - CNAME
  - LICENSE
gems:
  - jekyll-feed
  - jekyll-sitemap
permalink: /:categories/:title/
